### ISSUE TITLE
Extrair para um novo módulo

### ISSUE THREAD

**Issue by matheusgr** [mateusqc/jogodamemoria#15]
https://github.com/mateusqc/jogodamemoria/blob/db466036a55ca91b756263b93e99c4941893e996/frontend/src/components/Board/index.js#L36-L74

é possível extrair boa parte dessa lógica em um módulo a parte, para operar a parte de lógica de maneira mais controlada.

**Comment by mateusqc** [comment]
> https://github.com/mateusqc/jogodamemoria/blob/db466036a55ca91b756263b93e99c4941893e996/frontend/src/components/Board/index.js#L36-L74
> 
> é possível extrair boa parte dessa lógica em um módulo a parte, para operar a parte de lógica de maneira mais controlada.

De fato, possui muita lógica atrelada nessas funções. Mas quando o senhor diz "extrair em um módulo a parte", seria para levar para um arquivo de utils, por exemplo? Fico receoso pelo fato de haverem algumas manipulações de estado do próprio componente no decorrer das funções, o que provavelmente refletiria na necessidade de definições de callbacks nessas funções extraídas, o que talvez fosse até complicar um pouco mais.

Será que devido a isso, não seria melhor melhor manter esta lógica no próprio componente, tentando estruturar melhor (talvez extraindo outras funções, o que já foi feito) para que seja mantido o contexto de sua execução?

**Comment by mateusqc** [comment]
Alteração aplicada.
