### ISSUE TITLE
Props

### ISSUE THREAD

**Issue by camilacarvalho** [mateusqc/jogodamemoria#20]
https://github.com/mateusqc/jogodamemoria/blob/d1b8d8a837ffa8d65f4654c98ee0a71fbe2c6190/frontend/src/components/Board/index.js#L16

Oi Matheus, vi que você não está tirando vantagens do uso de desestruturação, acho que ajudaria a melhorar a legibilidade do código. Dá uma olhada nesse [site](https://medium.com/@lcriswell/destructuring-props-in-react-b1c295005ce0), lá explica melhor sobre isso.

**Comment by mateusqc** [comment]
> https://github.com/mateusqc/jogodamemoria/blob/d1b8d8a837ffa8d65f4654c98ee0a71fbe2c6190/frontend/src/components/Board/index.js#L16
> 
> Oi Matheus, vi que você não está tirando vantagens do uso de desestruturação, acho que ajudaria a melhorar a legibilidade do código. Dá uma olhada nesse [site](https://medium.com/@lcriswell/destructuring-props-in-react-b1c295005ce0), lá explica melhor sobre isso.

De fato, Camila! Ainda resta fazer proveito das desconstrução de props nesse componente em questão. Agradeço demais a sua sugestão, não o fiz ainda pois o mesmo estava passando por sucessivas mudanças. Farei isso assim que possível. Mais uma vez, muito obrigado!

**Comment by mateusqc** [comment]
Alteração aplicada.
