### ISSUE TITLE
Sugestão para projeto

### ISSUE THREAD

**Issue by joaobb** [mateusqc/jogodamemoria#6]
Opa meu bom, excelente projeto. 
Penso que só ficou faltando um README no back indicando como rodar o projeto, por questão de facilitar o uso mesmo.

**Comment by mateusqc** [comment]
> Opa meu bom, excelente projeto.
> Penso que só ficou faltando um README no back indicando como rodar o projeto, por questão de facilitar o uso mesmo.

Obrigado pela sugestão, criei um pequeno arquivo de README com essa instrução. Futuramente irei detalha-lo com mais informações da api. O PR da modificação é o #7.
